/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.walkme.domain.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class AggregatedActivities extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -5143284973158820243L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"AggregatedActivities\",\"namespace\":\"com.walkme.domain.avro\",\"fields\":[{\"name\":\"userId\",\"type\":\"string\"},{\"name\":\"environment\",\"type\":\"string\"},{\"name\":\"activities\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"SimplifiedActivity\",\"fields\":[{\"name\":\"activityType\",\"type\":\"string\"},{\"name\":\"startTimestamp\",\"type\":\"long\"},{\"name\":\"endTimestamp\",\"type\":[\"null\",\"long\"],\"default\":null}]}}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<AggregatedActivities> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<AggregatedActivities> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<AggregatedActivities> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<AggregatedActivities> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<AggregatedActivities> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this AggregatedActivities to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a AggregatedActivities from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a AggregatedActivities instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static AggregatedActivities fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.CharSequence userId;
  private java.lang.CharSequence environment;
  private java.util.List<com.walkme.domain.avro.SimplifiedActivity> activities;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public AggregatedActivities() {}

  /**
   * All-args constructor.
   * @param userId The new value for userId
   * @param environment The new value for environment
   * @param activities The new value for activities
   */
  public AggregatedActivities(java.lang.CharSequence userId, java.lang.CharSequence environment, java.util.List<com.walkme.domain.avro.SimplifiedActivity> activities) {
    this.userId = userId;
    this.environment = environment;
    this.activities = activities;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return userId;
    case 1: return environment;
    case 2: return activities;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: userId = (java.lang.CharSequence)value$; break;
    case 1: environment = (java.lang.CharSequence)value$; break;
    case 2: activities = (java.util.List<com.walkme.domain.avro.SimplifiedActivity>)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'userId' field.
   * @return The value of the 'userId' field.
   */
  public java.lang.CharSequence getUserId() {
    return userId;
  }


  /**
   * Sets the value of the 'userId' field.
   * @param value the value to set.
   */
  public void setUserId(java.lang.CharSequence value) {
    this.userId = value;
  }

  /**
   * Gets the value of the 'environment' field.
   * @return The value of the 'environment' field.
   */
  public java.lang.CharSequence getEnvironment() {
    return environment;
  }


  /**
   * Sets the value of the 'environment' field.
   * @param value the value to set.
   */
  public void setEnvironment(java.lang.CharSequence value) {
    this.environment = value;
  }

  /**
   * Gets the value of the 'activities' field.
   * @return The value of the 'activities' field.
   */
  public java.util.List<com.walkme.domain.avro.SimplifiedActivity> getActivities() {
    return activities;
  }


  /**
   * Sets the value of the 'activities' field.
   * @param value the value to set.
   */
  public void setActivities(java.util.List<com.walkme.domain.avro.SimplifiedActivity> value) {
    this.activities = value;
  }

  /**
   * Creates a new AggregatedActivities RecordBuilder.
   * @return A new AggregatedActivities RecordBuilder
   */
  public static com.walkme.domain.avro.AggregatedActivities.Builder newBuilder() {
    return new com.walkme.domain.avro.AggregatedActivities.Builder();
  }

  /**
   * Creates a new AggregatedActivities RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new AggregatedActivities RecordBuilder
   */
  public static com.walkme.domain.avro.AggregatedActivities.Builder newBuilder(com.walkme.domain.avro.AggregatedActivities.Builder other) {
    if (other == null) {
      return new com.walkme.domain.avro.AggregatedActivities.Builder();
    } else {
      return new com.walkme.domain.avro.AggregatedActivities.Builder(other);
    }
  }

  /**
   * Creates a new AggregatedActivities RecordBuilder by copying an existing AggregatedActivities instance.
   * @param other The existing instance to copy.
   * @return A new AggregatedActivities RecordBuilder
   */
  public static com.walkme.domain.avro.AggregatedActivities.Builder newBuilder(com.walkme.domain.avro.AggregatedActivities other) {
    if (other == null) {
      return new com.walkme.domain.avro.AggregatedActivities.Builder();
    } else {
      return new com.walkme.domain.avro.AggregatedActivities.Builder(other);
    }
  }

  /**
   * RecordBuilder for AggregatedActivities instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<AggregatedActivities>
    implements org.apache.avro.data.RecordBuilder<AggregatedActivities> {

    private java.lang.CharSequence userId;
    private java.lang.CharSequence environment;
    private java.util.List<com.walkme.domain.avro.SimplifiedActivity> activities;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.walkme.domain.avro.AggregatedActivities.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.userId)) {
        this.userId = data().deepCopy(fields()[0].schema(), other.userId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.environment)) {
        this.environment = data().deepCopy(fields()[1].schema(), other.environment);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.activities)) {
        this.activities = data().deepCopy(fields()[2].schema(), other.activities);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
    }

    /**
     * Creates a Builder by copying an existing AggregatedActivities instance
     * @param other The existing instance to copy.
     */
    private Builder(com.walkme.domain.avro.AggregatedActivities other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.userId)) {
        this.userId = data().deepCopy(fields()[0].schema(), other.userId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.environment)) {
        this.environment = data().deepCopy(fields()[1].schema(), other.environment);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.activities)) {
        this.activities = data().deepCopy(fields()[2].schema(), other.activities);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'userId' field.
      * @return The value.
      */
    public java.lang.CharSequence getUserId() {
      return userId;
    }


    /**
      * Sets the value of the 'userId' field.
      * @param value The value of 'userId'.
      * @return This builder.
      */
    public com.walkme.domain.avro.AggregatedActivities.Builder setUserId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.userId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'userId' field has been set.
      * @return True if the 'userId' field has been set, false otherwise.
      */
    public boolean hasUserId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'userId' field.
      * @return This builder.
      */
    public com.walkme.domain.avro.AggregatedActivities.Builder clearUserId() {
      userId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'environment' field.
      * @return The value.
      */
    public java.lang.CharSequence getEnvironment() {
      return environment;
    }


    /**
      * Sets the value of the 'environment' field.
      * @param value The value of 'environment'.
      * @return This builder.
      */
    public com.walkme.domain.avro.AggregatedActivities.Builder setEnvironment(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.environment = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'environment' field has been set.
      * @return True if the 'environment' field has been set, false otherwise.
      */
    public boolean hasEnvironment() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'environment' field.
      * @return This builder.
      */
    public com.walkme.domain.avro.AggregatedActivities.Builder clearEnvironment() {
      environment = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'activities' field.
      * @return The value.
      */
    public java.util.List<com.walkme.domain.avro.SimplifiedActivity> getActivities() {
      return activities;
    }


    /**
      * Sets the value of the 'activities' field.
      * @param value The value of 'activities'.
      * @return This builder.
      */
    public com.walkme.domain.avro.AggregatedActivities.Builder setActivities(java.util.List<com.walkme.domain.avro.SimplifiedActivity> value) {
      validate(fields()[2], value);
      this.activities = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'activities' field has been set.
      * @return True if the 'activities' field has been set, false otherwise.
      */
    public boolean hasActivities() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'activities' field.
      * @return This builder.
      */
    public com.walkme.domain.avro.AggregatedActivities.Builder clearActivities() {
      activities = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public AggregatedActivities build() {
      try {
        AggregatedActivities record = new AggregatedActivities();
        record.userId = fieldSetFlags()[0] ? this.userId : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.environment = fieldSetFlags()[1] ? this.environment : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.activities = fieldSetFlags()[2] ? this.activities : (java.util.List<com.walkme.domain.avro.SimplifiedActivity>) defaultValue(fields()[2]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<AggregatedActivities>
    WRITER$ = (org.apache.avro.io.DatumWriter<AggregatedActivities>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<AggregatedActivities>
    READER$ = (org.apache.avro.io.DatumReader<AggregatedActivities>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.userId);

    out.writeString(this.environment);

    long size0 = this.activities.size();
    out.writeArrayStart();
    out.setItemCount(size0);
    long actualSize0 = 0;
    for (com.walkme.domain.avro.SimplifiedActivity e0: this.activities) {
      actualSize0++;
      out.startItem();
      e0.customEncode(out);
    }
    out.writeArrayEnd();
    if (actualSize0 != size0)
      throw new java.util.ConcurrentModificationException("Array-size written was " + size0 + ", but element count was " + actualSize0 + ".");

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.userId = in.readString(this.userId instanceof Utf8 ? (Utf8)this.userId : null);

      this.environment = in.readString(this.environment instanceof Utf8 ? (Utf8)this.environment : null);

      long size0 = in.readArrayStart();
      java.util.List<com.walkme.domain.avro.SimplifiedActivity> a0 = this.activities;
      if (a0 == null) {
        a0 = new SpecificData.Array<com.walkme.domain.avro.SimplifiedActivity>((int)size0, SCHEMA$.getField("activities").schema());
        this.activities = a0;
      } else a0.clear();
      SpecificData.Array<com.walkme.domain.avro.SimplifiedActivity> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<com.walkme.domain.avro.SimplifiedActivity>)a0 : null);
      for ( ; 0 < size0; size0 = in.arrayNext()) {
        for ( ; size0 != 0; size0--) {
          com.walkme.domain.avro.SimplifiedActivity e0 = (ga0 != null ? ga0.peek() : null);
          if (e0 == null) {
            e0 = new com.walkme.domain.avro.SimplifiedActivity();
          }
          e0.customDecode(in);
          a0.add(e0);
        }
      }

    } else {
      for (int i = 0; i < 3; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.userId = in.readString(this.userId instanceof Utf8 ? (Utf8)this.userId : null);
          break;

        case 1:
          this.environment = in.readString(this.environment instanceof Utf8 ? (Utf8)this.environment : null);
          break;

        case 2:
          long size0 = in.readArrayStart();
          java.util.List<com.walkme.domain.avro.SimplifiedActivity> a0 = this.activities;
          if (a0 == null) {
            a0 = new SpecificData.Array<com.walkme.domain.avro.SimplifiedActivity>((int)size0, SCHEMA$.getField("activities").schema());
            this.activities = a0;
          } else a0.clear();
          SpecificData.Array<com.walkme.domain.avro.SimplifiedActivity> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<com.walkme.domain.avro.SimplifiedActivity>)a0 : null);
          for ( ; 0 < size0; size0 = in.arrayNext()) {
            for ( ; size0 != 0; size0--) {
              com.walkme.domain.avro.SimplifiedActivity e0 = (ga0 != null ? ga0.peek() : null);
              if (e0 == null) {
                e0 = new com.walkme.domain.avro.SimplifiedActivity();
              }
              e0.customDecode(in);
              a0.add(e0);
            }
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










